users:
  zjl:
    username: 周杰伦
    password: 1234abcd!
  notExistUser:
    username: BlueGlasses
    password: 12345

mysql:
  db: autotest
  host: localhost
  password: 123456
  port: 3306
  user: root


url: http://192.168.56.20